# CREATE REPORT BY USER
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Audi",
    "model": "A4",
    "year": 2018,
    "lng": 0,
    "lat": 0,
    "mileage": 20000,
    "price": 30000
}