### CREATE REPORT BY USER
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Mercedes",
    "model": "A5",
    "year": 2018,
    "lng": 0,
    "lat": 0,
    "mileage": 20000,
    "price": 30000
}

### APPROVE REPORT
PATCH http://localhost:3000/reports/4
Content-Type: application/json

{
    "approved": true
}

### QUERY REPORTS
GET http://localhost:3000/reports?make=Mercedes&model=A5&year=2018&lng=5&lat=0&mileage=19995&price=30000